version: "3.5"
services:
    jetson:
        container_name: ssd
        build:
            context: .
            dockerfile: Dockerfile    
        volumes:
            - /usr/local/cuda-10.0:/usr/local/cuda-10.0:ro
            - /usr/lib/aarch64-linux-gnu/libcudnn.so.7.3.1:/usr/lib/aarch64-linux-gnu/libcudnn.so.7.3.1:ro
            - /usr/lib/aarch64-linux-gnu/libnuma.so.1.0.0:/usr/lib/aarch64-linux-gnu/libnuma.so.1.0.0:ro
            - /usr/lib/aarch64-linux-gnu/tegra:/usr/lib/aarch64-linux-gnu/tegra:ro
            - /usr/lib/aarch64-linux-gnu/tegra-egl:/usr/lib/aarch64-linux-gnu/tegra-egl:ro
            - /usr/lib/aarch64-linux-gnu/gstreamer-1.0/:/usr/lib/aarch64-linux-gnu/gstreamer-1.0/:ro
            - /usr/lib/aarch64-linux-gnu/libgstnvivameta.so:/usr/lib/aarch64-linux-gnu/libgstnvivameta.so:ro
            - /usr/lib/aarch64-linux-gnu/libavfilter.so.6.107.100:/usr/lib/aarch64-linux-gnu/libavfilter.so.6.107.100:ro
            - /usr/lib/aarch64-linux-gnu/libgstnvegl-1.0.so.0:/usr/lib/aarch64-linux-gnu/libgstnvegl-1.0.so.0:ro
            - /usr/lib/aarch64-linux-gnu/libgstnvexifmeta.so:/usr/lib/aarch64-linux-gnu/libgstnvexifmeta.so:ro
            - /usr/lib/aarch64-linux-gnu/libLLVM-6.0.so.1:/usr/lib/aarch64-linux-gnu/libLLVM-6.0.so.1:ro
            - /usr/share/glvnd/egl_vendor.d/10_nvidia.json:/usr/share/glvnd/egl_vendor.d/10_nvidia.json:ro

